### ISSUE TITLE
Issue with preview

### ISSUE THREAD

**Issue by In4init3** [betwo/vscode-linux-binary-preview#10]
for some reason the "Unable to open file.so': Assertion Failed: argument is undefined or null."  and that is the entire error. can I have some help with the problem?

**Comment by In4init3** [comment]
Sorry for the late reply but it happens in on .so files, i am modding il2cpp applications so i am tryting to edit these files.

**Comment by betwo** [comment]
No worries. I think I was able to reproduce the error:
It also happens for me, if the `file` command is not correct.

Do you have that installed in your system, i.e. can you run `file <your-library.so>`?
I'm working on better error messages in the mean time.

**Comment by In4init3** [comment]
The issue has been fixed in the latest version, it is now asking to install the libraries (file, ldd, and nm) so that is my only issue for now.

**Comment by betwo** [comment]
ok, great. Which linux distro are you using? I have so far only added instructions for Ubuntu in the readme file.

**Comment by betwo** [comment]
> @betwo Need pycharm plugin, thank u!

Didn't see this, Sorry, can't help you with pycharm ;)

**Comment by betwo** [comment]
Closing this for now, please re-open if required!
