### ISSUE TITLE
archive file preview

### ISSUE THREAD

**Issue by xshrim** [betwo/vscode-linux-binary-preview#11]
could this extension add preview support for archive files(such as .rar, .zip, .tar, .tgz...) by using `tar -tf`, `zip -sf` and `unrar l` commands rather than just outputing file info.

**Comment by betwo** [comment]
Hey @xshrim, we can definitely add that. Do you want to contribute this, or is it okay if that takes a few days?

**Comment by betwo** [comment]
Version 2.3 adds support for archive files like you mentioned above.
in case something does not work as expected, please feel free to re-open this issue or create a new one (or open a pull-request).

Cheers
