### ISSUE TITLE
request support  linux_module.so.xx 

### ISSUE THREAD

**Issue by shenxiaolong-code** [betwo/vscode-linux-binary-preview#14]
Linux module will have name  xxxx.so.1, xxxx.so.2， xxxx.so.nn ， it is just the .so file with version number, expect supporting it.
e.g :
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fdbc18f2000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdbc18cf000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdbc18c9000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fdbc16e7000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdbc1598000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fdbc157b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdbc1389000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fdbd37e1000)

**Comment by betwo** [comment]
Thanks for the suggestion, will be part of version 2.4
